language: ruby
rvm:
- 2.0.0
notifications:
  slack:
    secure: YDKzu4hsN/VXhhbDNAElrQEcoC83G71LiHZRBXuLLg4K4BUO0TKkmRgAZnKVFJFR4dqr3BF1gnU1fJsmrdH4qLCgIk2vWsq+4c2ZeIbNjcP1U+Y8GEOVOI1uOegRBhqOBIttpbz923BKapwarTGBFs2NlLsCQGrAfSHcnfZDFmMAwas/ll2fOUZB/Fi9RKkXgStW+nRyh6wGtLVdQtC0IW4kHZFtRoON25nXTKg/6d//IynVNOUwV9NgmHSy3l1/TP4BgzrMyOxUETuJhoblifXI0CAI8pX1gaUXVJv4xzLGiGH+EVIOzx/lhGzFJhjAgjpzdy4t5AJUFxOPQtwuu/IZptplSY4EJy3i7vvuuGhLlavGD6cGnfpn0gx30erPY3BMXTUG+KWuADW5NEWMWUo5l9NSRWla+KfN7b8TNyB2MSWp7mGh4nhF7H/yYHa36tWQWjtvyqaROXCEkGSNOFgKPPEdcx3u5bLul8SX3JbPiICFpX2e0fiskf3qVKjwfQnWuJ7HWoTLGAX71m1dyY9OQvM9Re9megNLowNPBywjFFobKu2/u24j/8MJM6wh3rzMGcr6TqXpDy8llyHHaZe45BprZAn1lNy1lu/HCJUSVRdtSy3KbKJepSFsrf+SxkNZpyRMvVTTKBRFj74nlyoCh9gsisaDOPsIQUz/Zcg=
script: ruby tc_simple_number.rb
